services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t